//
// Role.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Role: JSONEncodable {
    public var clientCount: Int32?
    public var createdDate: Int64?
    public var id: Int32?
    public var locked: Bool?
    public var name: String?
    public var role: String?
    public var rolePermission: [Permission]?
    public var userCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["client_count"] = self.clientCount?.encodeToJSON()
        nillableDictionary["created_date"] = self.createdDate?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["locked"] = self.locked
        nillableDictionary["name"] = self.name
        nillableDictionary["role"] = self.role
        nillableDictionary["role_permission"] = self.rolePermission?.encodeToJSON()
        nillableDictionary["user_count"] = self.userCount?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
