//
// UserAchievementResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserAchievementResource: JSONEncodable {
    /** Flag indicating whether the user has earned the achievement */
    public var achieved: Bool?
    /** The achievement being tracked */
    public var achievementName: String?
    /** The date/time this resource was created in seconds since unix epoch */
    public var createdDate: Int64?
    /** The date/time the achievement was earned as a unix timestamp in seconds */
    public var earnedDate: Int64?
    /** The id of the achievement progress */
    public var id: String?
    /** The current progress of the user on the achievement */
    public var progress: Int32?
    /** The date/time this resource was last updated in seconds since unix epoch */
    public var updatedDate: Int64?
    /** The id of the user whose progress is being tracked */
    public var userId: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["achieved"] = self.achieved
        nillableDictionary["achievement_name"] = self.achievementName
        nillableDictionary["created_date"] = self.createdDate?.encodeToJSON()
        nillableDictionary["earned_date"] = self.earnedDate?.encodeToJSON()
        nillableDictionary["id"] = self.id
        nillableDictionary["progress"] = self.progress?.encodeToJSON()
        nillableDictionary["updated_date"] = self.updatedDate?.encodeToJSON()
        nillableDictionary["user_id"] = self.userId?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
