//
// CampaignsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class CampaignsAPI: APIBase {
    /**
     Add a challenge to a campaign
     - parameter id: (path) The id of the campaign 
     - parameter challengeId: (body) The id of the challenge (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addChallengeToCampaign(id: Int64, challengeId: Int64? = nil, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        addChallengeToCampaignWithRequestBuilder(id: id, challengeId: challengeId).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Add a challenge to a campaign
     - POST /campaigns/{id}/challenges
     - <b>Permissions Needed:</b> CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - parameter id: (path) The id of the campaign 
     - parameter challengeId: (body) The id of the challenge (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func addChallengeToCampaignWithRequestBuilder(id: Int64, challengeId: Int64? = nil) -> RequestBuilder<Void> {
        var path = "/campaigns/{id}/challenges"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = challengeId?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a campaign
     - parameter campaignResource: (body) The campaign resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createCampaign(campaignResource: CampaignResource? = nil, completion: @escaping ((_ data: CampaignResource?, _ error: ErrorResponse?) -> Void)) {
        createCampaignWithRequestBuilder(campaignResource: campaignResource).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a campaign
     - POST /campaigns
     - <b>Permissions Needed:</b> CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "template" : "template",
  "reward_set" : {
    "short_description" : "short_description",
    "unique_key" : "unique_key",
    "currency_rewards" : [ {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    }, {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    } ],
    "name" : "name",
    "created_date" : 7,
    "id" : 4,
    "long_description" : "long_description",
    "max_placing" : 6,
    "updated_date" : 7,
    "item_rewards" : [ {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    }, {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    } ]
  },
  "short_description" : "short_description",
  "next_challenge_date" : 1,
  "active" : false,
  "long_description" : "long_description",
  "leaderboard_strategy" : "leaderboard_strategy",
  "next_challenge" : "next_challenge",
  "name" : "name",
  "additional_properties" : {
    "key" : {
      "type" : "type"
    }
  },
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 5,
  "reward_status" : "pending"
}}]
     - parameter campaignResource: (body) The campaign resource object (optional)
     - returns: RequestBuilder<CampaignResource> 
     */
    open class func createCampaignWithRequestBuilder(campaignResource: CampaignResource? = nil) -> RequestBuilder<CampaignResource> {
        let path = "/campaigns"
        let URLString = JSAPIAPI.basePath + path
        let parameters = campaignResource?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CampaignResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a campaign template
     - parameter campaignTemplateResource: (body) The campaign template resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createCampaignTemplate(campaignTemplateResource: TemplateResource? = nil, completion: @escaping ((_ data: TemplateResource?, _ error: ErrorResponse?) -> Void)) {
        createCampaignTemplateWithRequestBuilder(campaignTemplateResource: campaignTemplateResource).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a campaign template
     - POST /campaigns/templates
     - Campaign Templates define a type of campaign and the properties they have. <br><br><b>Permissions Needed:</b> TEMPLATE_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "allow_additional" : false,
  "name" : "name",
  "created_date" : 0,
  "id" : "id",
  "updated_date" : 6,
  "properties" : [ {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  }, {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  } ]
}}]
     - parameter campaignTemplateResource: (body) The campaign template resource object (optional)
     - returns: RequestBuilder<TemplateResource> 
     */
    open class func createCampaignTemplateWithRequestBuilder(campaignTemplateResource: TemplateResource? = nil) -> RequestBuilder<TemplateResource> {
        let path = "/campaigns/templates"
        let URLString = JSAPIAPI.basePath + path
        let parameters = campaignTemplateResource?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<TemplateResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete a campaign
     - parameter id: (path) The campaign id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteCampaign(id: Int64, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteCampaignWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Delete a campaign
     - DELETE /campaigns/{id}
     - <b>Permissions Needed:</b> CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - parameter id: (path) The campaign id 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCampaignWithRequestBuilder(id: Int64) -> RequestBuilder<Void> {
        var path = "/campaigns/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Delete a campaign template
     - parameter id: (path) The id of the template 
     - parameter cascade: (query) The value needed to delete used templates (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteCampaignTemplate(id: String, cascade: String? = nil, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteCampaignTemplateWithRequestBuilder(id: id, cascade: cascade).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Delete a campaign template
     - DELETE /campaigns/templates/{id}
     - If cascade = 'detach', it will force delete the template even if it's attached to other objects. <br><br><b>Permissions Needed:</b> TEMPLATE_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - parameter id: (path) The id of the template 
     - parameter cascade: (query) The value needed to delete used templates (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCampaignTemplateWithRequestBuilder(id: String, cascade: String? = nil) -> RequestBuilder<Void> {
        var path = "/campaigns/templates/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "cascade": cascade
        ])

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Returns a single campaign
     - parameter id: (path) The campaign id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCampaign(id: Int64, completion: @escaping ((_ data: CampaignResource?, _ error: ErrorResponse?) -> Void)) {
        getCampaignWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns a single campaign
     - GET /campaigns/{id}
     - <b>Permissions Needed:</b> ANY
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "template" : "template",
  "reward_set" : {
    "short_description" : "short_description",
    "unique_key" : "unique_key",
    "currency_rewards" : [ {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    }, {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    } ],
    "name" : "name",
    "created_date" : 7,
    "id" : 4,
    "long_description" : "long_description",
    "max_placing" : 6,
    "updated_date" : 7,
    "item_rewards" : [ {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    }, {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    } ]
  },
  "short_description" : "short_description",
  "next_challenge_date" : 1,
  "active" : false,
  "long_description" : "long_description",
  "leaderboard_strategy" : "leaderboard_strategy",
  "next_challenge" : "next_challenge",
  "name" : "name",
  "additional_properties" : {
    "key" : {
      "type" : "type"
    }
  },
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 5,
  "reward_status" : "pending"
}}]
     - parameter id: (path) The campaign id 
     - returns: RequestBuilder<CampaignResource> 
     */
    open class func getCampaignWithRequestBuilder(id: Int64) -> RequestBuilder<CampaignResource> {
        var path = "/campaigns/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CampaignResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     List the challenges associated with a campaign
     - parameter id: (path) The campaign id 
     - parameter filterStartDate: (query) A comma separated string without spaces.  First value is the operator to search on, second value is the challenge start date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE). (optional)
     - parameter filterEndDate: (query) A comma separated string without spaces.  First value is the operator to search on, second value is the challenge end date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE). (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCampaignChallenges(id: Int64, filterStartDate: String? = nil, filterEndDate: String? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: @escaping ((_ data: PageResourceChallengeResource?, _ error: ErrorResponse?) -> Void)) {
        getCampaignChallengesWithRequestBuilder(id: id, filterStartDate: filterStartDate, filterEndDate: filterEndDate, size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List the challenges associated with a campaign
     - GET /campaigns/{id}/challenges
     - <b>Permissions Needed:</b> ANY
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "number" : 7,
  "last" : true,
  "size" : 1,
  "total_elements" : 1,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  }, {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  } ],
  "total_pages" : 6,
  "number_of_elements" : 1,
  "content" : [ {
    "end_date" : 5,
    "template" : "template",
    "reward_set" : {
      "short_description" : "short_description",
      "unique_key" : "unique_key",
      "currency_rewards" : [ {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      }, {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      } ],
      "name" : "name",
      "created_date" : 7,
      "id" : 4,
      "long_description" : "long_description",
      "max_placing" : 6,
      "updated_date" : 7,
      "item_rewards" : [ {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      }, {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      } ]
    },
    "short_description" : "short_description",
    "next_event_date" : 7,
    "long_description" : "long_description",
    "reward_lag_minutes" : 9,
    "leaderboard_strategy" : "leaderboard_strategy",
    "schedule" : {
      "duration" : 3,
      "repeat" : "DAILY",
      "duration_unit" : "millisecond"
    },
    "copy_of" : 1,
    "activities" : 0,
    "name" : "name",
    "additional_properties" : {
      "key" : {
        "type" : "type"
      }
    },
    "created_date" : 5,
    "id" : 2,
    "updated_date" : 4,
    "campaign_id" : 6,
    "start_date" : 2
  }, {
    "end_date" : 5,
    "template" : "template",
    "reward_set" : {
      "short_description" : "short_description",
      "unique_key" : "unique_key",
      "currency_rewards" : [ {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      }, {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      } ],
      "name" : "name",
      "created_date" : 7,
      "id" : 4,
      "long_description" : "long_description",
      "max_placing" : 6,
      "updated_date" : 7,
      "item_rewards" : [ {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      }, {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      } ]
    },
    "short_description" : "short_description",
    "next_event_date" : 7,
    "long_description" : "long_description",
    "reward_lag_minutes" : 9,
    "leaderboard_strategy" : "leaderboard_strategy",
    "schedule" : {
      "duration" : 3,
      "repeat" : "DAILY",
      "duration_unit" : "millisecond"
    },
    "copy_of" : 1,
    "activities" : 0,
    "name" : "name",
    "additional_properties" : {
      "key" : {
        "type" : "type"
      }
    },
    "created_date" : 5,
    "id" : 2,
    "updated_date" : 4,
    "campaign_id" : 6,
    "start_date" : 2
  } ],
  "first" : true
}}]
     - parameter id: (path) The campaign id 
     - parameter filterStartDate: (query) A comma separated string without spaces.  First value is the operator to search on, second value is the challenge start date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE). (optional)
     - parameter filterEndDate: (query) A comma separated string without spaces.  First value is the operator to search on, second value is the challenge end date, a unix timestamp in seconds.  Allowed operators: (GT, LT, EQ, GOE, LOE). (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - returns: RequestBuilder<PageResourceChallengeResource> 
     */
    open class func getCampaignChallengesWithRequestBuilder(id: Int64, filterStartDate: String? = nil, filterEndDate: String? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceChallengeResource> {
        var path = "/campaigns/{id}/challenges"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filter_start_date": filterStartDate, 
            "filter_end_date": filterEndDate, 
            "size": size?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "order": order
        ])

        let requestBuilder: RequestBuilder<PageResourceChallengeResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a single campaign template
     - parameter id: (path) The id of the template 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCampaignTemplate(id: String, completion: @escaping ((_ data: TemplateResource?, _ error: ErrorResponse?) -> Void)) {
        getCampaignTemplateWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a single campaign template
     - GET /campaigns/templates/{id}
     - <b>Permissions Needed:</b> TEMPLATE_ADMIN or CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "allow_additional" : false,
  "name" : "name",
  "created_date" : 0,
  "id" : "id",
  "updated_date" : 6,
  "properties" : [ {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  }, {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  } ]
}}]
     - parameter id: (path) The id of the template 
     - returns: RequestBuilder<TemplateResource> 
     */
    open class func getCampaignTemplateWithRequestBuilder(id: String) -> RequestBuilder<TemplateResource> {
        var path = "/campaigns/templates/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<TemplateResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     List and search campaign templates
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCampaignTemplates(size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: @escaping ((_ data: PageResourceTemplateResource?, _ error: ErrorResponse?) -> Void)) {
        getCampaignTemplatesWithRequestBuilder(size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List and search campaign templates
     - GET /campaigns/templates
     - <b>Permissions Needed:</b> TEMPLATE_ADMIN or CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "number" : 1,
  "last" : true,
  "size" : 5,
  "total_elements" : 2,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  }, {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  } ],
  "total_pages" : 7,
  "number_of_elements" : 5,
  "content" : [ {
    "allow_additional" : false,
    "name" : "name",
    "created_date" : 0,
    "id" : "id",
    "updated_date" : 6,
    "properties" : [ {
      "friendly_name" : "friendly_name",
      "option_value_path" : "path.to.value",
      "option_label_path" : "path.to.label",
      "name" : "name",
      "description" : "description",
      "options_url" : "options_url",
      "type" : "type",
      "field_list" : {
        "property_definition_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ],
        "property_type" : "property_type",
        "property_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ]
      },
      "required" : false
    }, {
      "friendly_name" : "friendly_name",
      "option_value_path" : "path.to.value",
      "option_label_path" : "path.to.label",
      "name" : "name",
      "description" : "description",
      "options_url" : "options_url",
      "type" : "type",
      "field_list" : {
        "property_definition_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ],
        "property_type" : "property_type",
        "property_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ]
      },
      "required" : false
    } ]
  }, {
    "allow_additional" : false,
    "name" : "name",
    "created_date" : 0,
    "id" : "id",
    "updated_date" : 6,
    "properties" : [ {
      "friendly_name" : "friendly_name",
      "option_value_path" : "path.to.value",
      "option_label_path" : "path.to.label",
      "name" : "name",
      "description" : "description",
      "options_url" : "options_url",
      "type" : "type",
      "field_list" : {
        "property_definition_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ],
        "property_type" : "property_type",
        "property_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ]
      },
      "required" : false
    }, {
      "friendly_name" : "friendly_name",
      "option_value_path" : "path.to.value",
      "option_label_path" : "path.to.label",
      "name" : "name",
      "description" : "description",
      "options_url" : "options_url",
      "type" : "type",
      "field_list" : {
        "property_definition_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ],
        "property_type" : "property_type",
        "property_fields" : [ {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        }, {
          "inner_type" : "integer",
          "valid_values" : [ "valid_values", "valid_values" ],
          "name" : "name",
          "description" : "description",
          "type" : "integer",
          "inner_type_fields" : [ null, null ],
          "required" : false
        } ]
      },
      "required" : false
    } ]
  } ],
  "first" : true
}}]
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - returns: RequestBuilder<PageResourceTemplateResource> 
     */
    open class func getCampaignTemplatesWithRequestBuilder(size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceTemplateResource> {
        let path = "/campaigns/templates"
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "size": size?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "order": order
        ])

        let requestBuilder: RequestBuilder<PageResourceTemplateResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     List and search campaigns
     - parameter filterActive: (query) Filter for campaigns that are active (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCampaigns(filterActive: Bool? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: @escaping ((_ data: PageResourceCampaignResource?, _ error: ErrorResponse?) -> Void)) {
        getCampaignsWithRequestBuilder(filterActive: filterActive, size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List and search campaigns
     - GET /campaigns
     - <b>Permissions Needed:</b> ANY
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "number" : 5,
  "last" : true,
  "size" : 7,
  "total_elements" : 9,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  }, {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  } ],
  "total_pages" : 3,
  "number_of_elements" : 2,
  "content" : [ {
    "template" : "template",
    "reward_set" : {
      "short_description" : "short_description",
      "unique_key" : "unique_key",
      "currency_rewards" : [ {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      }, {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      } ],
      "name" : "name",
      "created_date" : 7,
      "id" : 4,
      "long_description" : "long_description",
      "max_placing" : 6,
      "updated_date" : 7,
      "item_rewards" : [ {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      }, {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      } ]
    },
    "short_description" : "short_description",
    "next_challenge_date" : 1,
    "active" : false,
    "long_description" : "long_description",
    "leaderboard_strategy" : "leaderboard_strategy",
    "next_challenge" : "next_challenge",
    "name" : "name",
    "additional_properties" : {
      "key" : {
        "type" : "type"
      }
    },
    "created_date" : 0,
    "id" : 6,
    "updated_date" : 5,
    "reward_status" : "pending"
  }, {
    "template" : "template",
    "reward_set" : {
      "short_description" : "short_description",
      "unique_key" : "unique_key",
      "currency_rewards" : [ {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      }, {
        "currency_name" : "currency_name",
        "max_rank" : 9,
        "min_rank" : 3,
        "percent" : false,
        "value" : 2.027123023002322,
        "currency_code" : "currency_code"
      } ],
      "name" : "name",
      "created_date" : 7,
      "id" : 4,
      "long_description" : "long_description",
      "max_placing" : 6,
      "updated_date" : 7,
      "item_rewards" : [ {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      }, {
        "quantity" : 1,
        "item_id" : 7,
        "max_rank" : 1,
        "item_name" : "item_name",
        "min_rank" : 1
      } ]
    },
    "short_description" : "short_description",
    "next_challenge_date" : 1,
    "active" : false,
    "long_description" : "long_description",
    "leaderboard_strategy" : "leaderboard_strategy",
    "next_challenge" : "next_challenge",
    "name" : "name",
    "additional_properties" : {
      "key" : {
        "type" : "type"
      }
    },
    "created_date" : 0,
    "id" : 6,
    "updated_date" : 5,
    "reward_status" : "pending"
  } ],
  "first" : true
}}]
     - parameter filterActive: (query) Filter for campaigns that are active (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - returns: RequestBuilder<PageResourceCampaignResource> 
     */
    open class func getCampaignsWithRequestBuilder(filterActive: Bool? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceCampaignResource> {
        let path = "/campaigns"
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filter_active": filterActive, 
            "size": size?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "order": order
        ])

        let requestBuilder: RequestBuilder<PageResourceCampaignResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Remove a challenge from a campaign
     - parameter campaignId: (path) The campaign id 
     - parameter id: (path) The challenge id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func removeChallengeFromCampaign(campaignId: Int64, id: Int64, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        removeChallengeFromCampaignWithRequestBuilder(campaignId: campaignId, id: id).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Remove a challenge from a campaign
     - DELETE /campaigns/{campaign_id}/challenges/{id}
     - <b>Permissions Needed:</b> CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - parameter campaignId: (path) The campaign id 
     - parameter id: (path) The challenge id 
     - returns: RequestBuilder<Void> 
     */
    open class func removeChallengeFromCampaignWithRequestBuilder(campaignId: Int64, id: Int64) -> RequestBuilder<Void> {
        var path = "/campaigns/{campaign_id}/challenges/{id}"
        path = path.replacingOccurrences(of: "{campaign_id}", with: "\(campaignId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a campaign
     - parameter id: (path) The campaign id 
     - parameter campaignResource: (body) The campaign resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateCampaign(id: Int64, campaignResource: CampaignResource? = nil, completion: @escaping ((_ data: CampaignResource?, _ error: ErrorResponse?) -> Void)) {
        updateCampaignWithRequestBuilder(id: id, campaignResource: campaignResource).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update a campaign
     - PUT /campaigns/{id}
     - <b>Permissions Needed:</b> CAMPAIGNS_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "template" : "template",
  "reward_set" : {
    "short_description" : "short_description",
    "unique_key" : "unique_key",
    "currency_rewards" : [ {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    }, {
      "currency_name" : "currency_name",
      "max_rank" : 9,
      "min_rank" : 3,
      "percent" : false,
      "value" : 2.027123023002322,
      "currency_code" : "currency_code"
    } ],
    "name" : "name",
    "created_date" : 7,
    "id" : 4,
    "long_description" : "long_description",
    "max_placing" : 6,
    "updated_date" : 7,
    "item_rewards" : [ {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    }, {
      "quantity" : 1,
      "item_id" : 7,
      "max_rank" : 1,
      "item_name" : "item_name",
      "min_rank" : 1
    } ]
  },
  "short_description" : "short_description",
  "next_challenge_date" : 1,
  "active" : false,
  "long_description" : "long_description",
  "leaderboard_strategy" : "leaderboard_strategy",
  "next_challenge" : "next_challenge",
  "name" : "name",
  "additional_properties" : {
    "key" : {
      "type" : "type"
    }
  },
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 5,
  "reward_status" : "pending"
}}]
     - parameter id: (path) The campaign id 
     - parameter campaignResource: (body) The campaign resource object (optional)
     - returns: RequestBuilder<CampaignResource> 
     */
    open class func updateCampaignWithRequestBuilder(id: Int64, campaignResource: CampaignResource? = nil) -> RequestBuilder<CampaignResource> {
        var path = "/campaigns/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = campaignResource?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<CampaignResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Update an campaign template
     - parameter id: (path) The id of the template 
     - parameter campaignTemplateResource: (body) The campaign template resource object (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateCampaignTemplate(id: String, campaignTemplateResource: TemplateResource? = nil, completion: @escaping ((_ data: TemplateResource?, _ error: ErrorResponse?) -> Void)) {
        updateCampaignTemplateWithRequestBuilder(id: id, campaignTemplateResource: campaignTemplateResource).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update an campaign template
     - PUT /campaigns/templates/{id}
     - <b>Permissions Needed:</b> TEMPLATE_ADMIN
     - OAuth:
       - type: oauth2
       - name: oauth2_client_credentials_grant     - OAuth:
       - type: oauth2
       - name: oauth2_password_grant
     - examples: [{contentType=application/json, example={
  "allow_additional" : false,
  "name" : "name",
  "created_date" : 0,
  "id" : "id",
  "updated_date" : 6,
  "properties" : [ {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  }, {
    "friendly_name" : "friendly_name",
    "option_value_path" : "path.to.value",
    "option_label_path" : "path.to.label",
    "name" : "name",
    "description" : "description",
    "options_url" : "options_url",
    "type" : "type",
    "field_list" : {
      "property_definition_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ],
      "property_type" : "property_type",
      "property_fields" : [ {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      }, {
        "inner_type" : "integer",
        "valid_values" : [ "valid_values", "valid_values" ],
        "name" : "name",
        "description" : "description",
        "type" : "integer",
        "inner_type_fields" : [ null, null ],
        "required" : false
      } ]
    },
    "required" : false
  } ]
}}]
     - parameter id: (path) The id of the template 
     - parameter campaignTemplateResource: (body) The campaign template resource object (optional)
     - returns: RequestBuilder<TemplateResource> 
     */
    open class func updateCampaignTemplateWithRequestBuilder(id: String, campaignTemplateResource: TemplateResource? = nil) -> RequestBuilder<TemplateResource> {
        var path = "/campaigns/templates/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = campaignTemplateResource?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<TemplateResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
