//
// DevicesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DevicesAPI: APIBase {
    /**
     Add device users
     - parameter userResources: (body) userResources 
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addDeviceUsers(userResources: [SimpleUserResource], id: Int32, completion: @escaping ((_ data: DeviceResource?, _ error: ErrorResponse?) -> Void)) {
        addDeviceUsersWithRequestBuilder(userResources: userResources, id: id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Add device users
     - POST /devices/{id}/users

     - examples: [{contentType=application/json, example={
  "data" : {
    "key" : "data"
  },
  "os" : "os",
  "description" : "description",
  "device_type" : "device_type",
  "users" : [ {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  }, {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  } ],
  "authorization" : "authorization",
  "condition" : "New",
  "serial" : "serial",
  "mac_address" : "mac_address",
  "name" : "name",
  "location" : "location",
  "model" : "model",
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 1,
  "make" : "make",
  "user" : {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  },
  "status" : "Active"
}}]
     - parameter userResources: (body) userResources 
     - parameter id: (path) id 
     - returns: RequestBuilder<DeviceResource> 
     */
    open class func addDeviceUsersWithRequestBuilder(userResources: [SimpleUserResource], id: Int32) -> RequestBuilder<DeviceResource> {
        var path = "/devices/{id}/users"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = userResources.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DeviceResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create a device
     - parameter device: (body) device 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createDevice(device: DeviceResource, completion: @escaping ((_ data: DeviceResource?, _ error: ErrorResponse?) -> Void)) {
        createDeviceWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a device
     - POST /devices

     - examples: [{contentType=application/json, example={
  "data" : {
    "key" : "data"
  },
  "os" : "os",
  "description" : "description",
  "device_type" : "device_type",
  "users" : [ {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  }, {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  } ],
  "authorization" : "authorization",
  "condition" : "New",
  "serial" : "serial",
  "mac_address" : "mac_address",
  "name" : "name",
  "location" : "location",
  "model" : "model",
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 1,
  "make" : "make",
  "user" : {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  },
  "status" : "Active"
}}]
     - parameter device: (body) device 
     - returns: RequestBuilder<DeviceResource> 
     */
    open class func createDeviceWithRequestBuilder(device: DeviceResource) -> RequestBuilder<DeviceResource> {
        let path = "/devices"
        let URLString = JSAPIAPI.basePath + path
        let parameters = device.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DeviceResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete a device
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteDevice(id: Int32, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteDeviceWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Delete a device
     - DELETE /devices/{id}

     - parameter id: (path) id 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteDeviceWithRequestBuilder(id: Int32) -> RequestBuilder<Void> {
        var path = "/devices/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Delete a device user
     - parameter id: (path) The id of the device 
     - parameter userId: (path) The user id of the device user 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteDeviceUser(id: Int32, userId: Int32, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteDeviceUserWithRequestBuilder(id: id, userId: userId).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Delete a device user
     - DELETE /devices/{id}/users/{user_id}

     - parameter id: (path) The id of the device 
     - parameter userId: (path) The user id of the device user 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteDeviceUserWithRequestBuilder(id: Int32, userId: Int32) -> RequestBuilder<Void> {
        var path = "/devices/{id}/users/{user_id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{user_id}", with: "\(userId)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Delete all device users
     - parameter id: (path) The id of the device 
     - parameter filterId: (query) Filter for device users to delete with a user id in a given comma separated list of ids (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteDeviceUsers(id: Int32, filterId: String? = nil, completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteDeviceUsersWithRequestBuilder(id: id, filterId: filterId).execute { (response, error) -> Void in
            completion(error)
        }
    }


    /**
     Delete all device users
     - DELETE /devices/{id}/users

     - parameter id: (path) The id of the device 
     - parameter filterId: (query) Filter for device users to delete with a user id in a given comma separated list of ids (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func deleteDeviceUsersWithRequestBuilder(id: Int32, filterId: String? = nil) -> RequestBuilder<Void> {
        var path = "/devices/{id}/users"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filter_id": filterId
        ])

        let requestBuilder: RequestBuilder<Void>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a single device
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDevice(id: Int32, completion: @escaping ((_ data: DeviceResource?, _ error: ErrorResponse?) -> Void)) {
        getDeviceWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a single device
     - GET /devices/{id}

     - examples: [{contentType=application/json, example={
  "data" : {
    "key" : "data"
  },
  "os" : "os",
  "description" : "description",
  "device_type" : "device_type",
  "users" : [ {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  }, {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  } ],
  "authorization" : "authorization",
  "condition" : "New",
  "serial" : "serial",
  "mac_address" : "mac_address",
  "name" : "name",
  "location" : "location",
  "model" : "model",
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 1,
  "make" : "make",
  "user" : {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  },
  "status" : "Active"
}}]
     - parameter id: (path) id 
     - returns: RequestBuilder<DeviceResource> 
     */
    open class func getDeviceWithRequestBuilder(id: Int32) -> RequestBuilder<DeviceResource> {
        var path = "/devices/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DeviceResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     List and search devices
     - parameter filterMake: (query) Filter for devices with specified make (optional)
     - parameter filterModel: (query) Filter for devices with specified model (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDevices(filterMake: String? = nil, filterModel: String? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil, completion: @escaping ((_ data: PageResourceDeviceResource?, _ error: ErrorResponse?) -> Void)) {
        getDevicesWithRequestBuilder(filterMake: filterMake, filterModel: filterModel, size: size, page: page, order: order).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List and search devices
     - GET /devices
     - Get a list of devices with optional filtering

     - examples: [{contentType=application/json, example={
  "number" : 5,
  "last" : true,
  "size" : 2,
  "total_elements" : 7,
  "sort" : [ {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  }, {
    "ignore_case" : true,
    "null_handling" : "NATIVE",
    "property" : "property",
    "ascending" : true,
    "descending" : true,
    "direction" : "ASC"
  } ],
  "total_pages" : 9,
  "number_of_elements" : 5,
  "content" : [ {
    "data" : {
      "key" : "data"
    },
    "os" : "os",
    "description" : "description",
    "device_type" : "device_type",
    "users" : [ {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    }, {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    } ],
    "authorization" : "authorization",
    "condition" : "New",
    "serial" : "serial",
    "mac_address" : "mac_address",
    "name" : "name",
    "location" : "location",
    "model" : "model",
    "created_date" : 0,
    "id" : 6,
    "updated_date" : 1,
    "make" : "make",
    "user" : {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    },
    "status" : "Active"
  }, {
    "data" : {
      "key" : "data"
    },
    "os" : "os",
    "description" : "description",
    "device_type" : "device_type",
    "users" : [ {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    }, {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    } ],
    "authorization" : "authorization",
    "condition" : "New",
    "serial" : "serial",
    "mac_address" : "mac_address",
    "name" : "name",
    "location" : "location",
    "model" : "model",
    "created_date" : 0,
    "id" : 6,
    "updated_date" : 1,
    "make" : "make",
    "user" : {
      "avatar_url" : "avatar_url",
      "id" : 1,
      "display_name" : "display_name",
      "username" : "username"
    },
    "status" : "Active"
  } ],
  "first" : true
}}]
     - parameter filterMake: (query) Filter for devices with specified make (optional)
     - parameter filterModel: (query) Filter for devices with specified model (optional)
     - parameter size: (query) The number of objects returned per page (optional, default to 25)
     - parameter page: (query) The number of the page returned, starting with 1 (optional, default to 1)
     - parameter order: (query) A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)
     - returns: RequestBuilder<PageResourceDeviceResource> 
     */
    open class func getDevicesWithRequestBuilder(filterMake: String? = nil, filterModel: String? = nil, size: Int32? = nil, page: Int32? = nil, order: String? = nil) -> RequestBuilder<PageResourceDeviceResource> {
        let path = "/devices"
        let URLString = JSAPIAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filter_make": filterMake, 
            "filter_model": filterModel, 
            "size": size?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "order": order
        ])

        let requestBuilder: RequestBuilder<PageResourceDeviceResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a device
     - parameter device: (body) device 
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateDevice(device: DeviceResource, id: Int32, completion: @escaping ((_ data: DeviceResource?, _ error: ErrorResponse?) -> Void)) {
        updateDeviceWithRequestBuilder(device: device, id: id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update a device
     - PUT /devices/{id}

     - examples: [{contentType=application/json, example={
  "data" : {
    "key" : "data"
  },
  "os" : "os",
  "description" : "description",
  "device_type" : "device_type",
  "users" : [ {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  }, {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  } ],
  "authorization" : "authorization",
  "condition" : "New",
  "serial" : "serial",
  "mac_address" : "mac_address",
  "name" : "name",
  "location" : "location",
  "model" : "model",
  "created_date" : 0,
  "id" : 6,
  "updated_date" : 1,
  "make" : "make",
  "user" : {
    "avatar_url" : "avatar_url",
    "id" : 1,
    "display_name" : "display_name",
    "username" : "username"
  },
  "status" : "Active"
}}]
     - parameter device: (body) device 
     - parameter id: (path) id 
     - returns: RequestBuilder<DeviceResource> 
     */
    open class func updateDeviceWithRequestBuilder(device: DeviceResource, id: Int32) -> RequestBuilder<DeviceResource> {
        var path = "/devices/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = JSAPIAPI.basePath + path
        let parameters = device.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DeviceResource>.Type = JSAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
