//
// ActionVariableResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ActionVariableResource: JSONEncodable {

    /** The name of the variable */
    public var name: String?
    /** Whether this variable is optional and can be left out/null */
    public var _optional: Bool?
    /** The type of the variable (see variable type endpoint for list) */
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["optional"] = self._optional
        nillableDictionary["type"] = self.type

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
