//
// Item.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Item: JSONEncodable {
    /** A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type, or be an extra not from the template */
    public var additionalProperties: [String:Property]?
    /** The behaviors linked to the item, describing various options and interactions. May not be included in item lists */
    public var behaviors: [Behavior]?
    /** A category for filtering items */
    public var category: String?
    /** The date the item was created, unix timestamp in seconds */
    public var createdDate: Int64?
    /** The id of the item */
    public var id: Int32?
    /** A long description of the item */
    public var longDescription: String?
    /** The name of the item */
    public var name: String?
    /** A short description of the item, max 255 chars */
    public var shortDescription: String?
    /** A number to use in sorting items.  Default 500 */
    public var sort: Int32?
    /** List of tags used for filtering items */
    public var tags: [String]?
    /** An item template this item is validated against.  May be null and no validation of additional_properties will be done.  Default &#x3D; null */
    public var template: String?
    /** The type of the item */
    public var typeHint: String?
    /** The unique key for the item */
    public var uniqueKey: String?
    /** The date the item was last updated, unix timestamp in seconds */
    public var updatedDate: Int64?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["additional_properties"] = self.additionalProperties?.encodeToJSON()
        nillableDictionary["behaviors"] = self.behaviors?.encodeToJSON()
        nillableDictionary["category"] = self.category
        nillableDictionary["created_date"] = self.createdDate?.encodeToJSON()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["long_description"] = self.longDescription
        nillableDictionary["name"] = self.name
        nillableDictionary["short_description"] = self.shortDescription
        nillableDictionary["sort"] = self.sort?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["template"] = self.template
        nillableDictionary["type_hint"] = self.typeHint
        nillableDictionary["unique_key"] = self.uniqueKey
        nillableDictionary["updated_date"] = self.updatedDate?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
