//
// PaymentMethodTypeResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PaymentMethodTypeResource: JSONEncodable {

    /** The id of the payment method type */
    public var id: Int32?
    /** The maximum timelimit in hours for an invoice in the processing status while waiting on this payment method type. Defaults to the global config invoice.processing_expiration_hours if null */
    public var invoiceProcessingHours: Int32?
    /** The name of the payment method type */
    public var name: String?
    /** Whether the payment handler supports the authorize and capture flow */
    public var supportsCapture: Bool?
    /** Whether the payment handler supports paying for part of an invoice, rather than the full grand_total */
    public var supportsPartial: Bool?
    /** Whether the payment handler supports rebilling the method later (for saved payments or subscriptions) */
    public var supportsRebill: Bool?
    /** Whether the payment handler supports refunding */
    public var supportsRefunds: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["invoice_processing_hours"] = self.invoiceProcessingHours?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["supports_capture"] = self.supportsCapture
        nillableDictionary["supports_partial"] = self.supportsPartial
        nillableDictionary["supports_rebill"] = self.supportsRebill
        nillableDictionary["supports_refunds"] = self.supportsRefunds

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
