//
// PredicateResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PredicateResource: JSONEncodable {
    /** The arguments the operator apply to. See notes for details. */
    public var args: [ExpressionResource]?
    /** The operator to be used in this predicate. See notes for details. */
    public var op: String?
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["args"] = self.args?.encodeToJSON()
        nillableDictionary["op"] = self.op
        nillableDictionary["type"] = self.type
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
