//
// ResourceTypeDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ResourceTypeDescription: JSONEncodable {

    /** The field on the resource that the id is in */
    public var idField: String?
    /** The unique name for the resource in swagger. This serves as the unique identifier. Cannot be changed after creation */
    public var name: String?
    /** The base path of the service */
    public var servicePath: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id_field"] = self.idField
        nillableDictionary["name"] = self.name
        nillableDictionary["service_path"] = self.servicePath

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
