//
// Schedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Schedule: JSONEncodable {

    public enum DurationUnit: String { 
        case millisecond = "millisecond"
        case second = "second"
        case minute = "minute"
        case hour = "hour"
        case day = "day"
        case week = "week"
        case month = "month"
        case year = "year"
    }
    public enum Repeat: String { 
        case daily = "DAILY"
        case weekly = "WEEKLY"
    }
    /** The duration of the repeatable events */
    public var duration: Int32?
    /** The unit of time for the duration field */
    public var durationUnit: DurationUnit?
    /** How often the event is scheduled */
    public var repeat: Repeat?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["duration_unit"] = self.durationUnit?.rawValue
        nillableDictionary["repeat"] = self.repeat?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
