//
// SqlDatabaseConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SqlDatabaseConfig: JSONEncodable {
    public var connectionPoolSize: Int32?
    public var dbName: String?
    public var hostname: String?
    public var password: String?
    public var port: Int32?
    public var username: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["connection_pool_size"] = self.connectionPoolSize?.encodeToJSON()
        nillableDictionary["db_name"] = self.dbName
        nillableDictionary["hostname"] = self.hostname
        nillableDictionary["password"] = self.password
        nillableDictionary["port"] = self.port?.encodeToJSON()
        nillableDictionary["username"] = self.username
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
