//
// SubscriptionPriceOverrideRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SubscriptionPriceOverrideRequest: JSONEncodable {

    /** The recurring price that has been set to override the base price. Null if not overriding */
    public var newPrice: Double?
    /** An explanation for the reason the price is being overridden */
    public var reason: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["new_price"] = self.newPrice
        nillableDictionary["reason"] = self.reason

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
