//
// VendorEmailLookupResource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Expressions are instructions for the rule engine to resolve certain values. For example instead of &#x60;user 1&#x60; it&#39;d state &#x60;user provided by the event&#x60;. Full list and definitions available at GET /bre/expressions. */
open class VendorEmailLookupResource: JSONEncodable {

    public var definition: String?
    public var lookupKey: ExpressionResource?
    public var requiredKeyType: String?
    public var type: String?
    public var valueType: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["definition"] = self.definition
        nillableDictionary["lookup_key"] = self.lookupKey?.encodeToJSON()
        nillableDictionary["required_key_type"] = self.requiredKeyType
        nillableDictionary["type"] = self.type
        nillableDictionary["value_type"] = self.valueType

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
